service: youtube-task-fampay
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    SERVICE_NAME: "${self:service}-${self:provider.stage}"
    STAGE: "${self:provider.stage, dev}"

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  YoutubeCorn: ${file(./Resources/LambdaResources/YoutubeCorn.yml)}

resources:
  Resources:
    YouTubeDataTable: ${file(./Resources/DynamoResources/YouTubeDataTable.yml)}