name: youtube-task-BE Development Server Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_KEY }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET }}
        aws-region: ${{ secrets.DEV_AWS_REGION }}          
    - name: Installing Node Modules
      run: |
        npm cache clean --force
        rm -rf node_modules
        npm i
    - name: Installing Serverless Framework
      run: npm install -g serverless
    - name: Code Format Checking
      run: npm run formatCheck
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.DEV_AWS_KEY }} --secret ${{ secrets.DEV_AWS_SECRET }} --profile ${{ secrets.DEV_PROFILE_NAME }}
    - name: Deploy Lambda functions
      run: |
        git config --global user.email ${{ secrets.GH_EMAIL }}
        git config --global user.name ${{ secrets.GH_USERNAME }}
        git remote set-url origin https://${{ secrets.GH_PERSONAL_TOKEN }}@github.com/${{ secrets.GH_USERNAME }}/devrook-BE.git
        sls deploy --stage dev --region ${{ secrets.DEV_AWS_REGION }}
